name: e_commerce_q1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  timer_builder: ^2.0.0
  flutter_animate: ^4.4.0
  provider: ^6.1.1
  flutter_staggered_grid_view: ^0.4.0
  intl: 0.18.1
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  firebase_ui_auth: ^1.13.1
 
  

 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/1.jpeg
    - assets/2.jpeg
    - assets/11.jpeg
    - assets/12.jpeg
    - assets/3.jpeg
    - assets/4.jpeg
    - assets/5.jpeg
    - assets/6.jpeg
    - assets/7.jpeg
    - assets/8.jpeg
    - assets/9.jpeg
    - assets/10.jpeg
    - assets/13.jpeg
    - assets/14.jpeg
   
 