// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf_MEfQ75benNmcTDOoyUjlGrAZ9BNQUE',
    appId: '1:618963328382:web:d24b6583ba9c5f13d1e72f',
    messagingSenderId: '618963328382',
    projectId: 'complete-641ab',
    authDomain: 'complete-641ab.firebaseapp.com',
    storageBucket: 'complete-641ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqgqxRdVaKqFUV-AVlXcksv-rPjkJOgig',
    appId: '1:618963328382:android:b6ccd8adec97c7b7d1e72f',
    messagingSenderId: '618963328382',
    projectId: 'complete-641ab',
    storageBucket: 'complete-641ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI_fHOJFRYkfnYXwIiWjlaJNy4WmCq5lU',
    appId: '1:618963328382:ios:994e50858c62440ad1e72f',
    messagingSenderId: '618963328382',
    projectId: 'complete-641ab',
    storageBucket: 'complete-641ab.appspot.com',
    iosBundleId: 'com.example.eCommerceQ1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI_fHOJFRYkfnYXwIiWjlaJNy4WmCq5lU',
    appId: '1:618963328382:ios:9f2051fb8e4e4068d1e72f',
    messagingSenderId: '618963328382',
    projectId: 'complete-641ab',
    storageBucket: 'complete-641ab.appspot.com',
    iosBundleId: 'com.example.eCommerceQ1.RunnerTests',
  );
}
